src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $duree;

   

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu_Formation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lieuFormation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $coutFormation;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $matSupp;

    /**
     * @ORM\ManyToOne(targetEntity=SessionFormation::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $sessionFormation;

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDuree(): ?string
    {
        return $this->duree;
    }

    public function setDuree(?string $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

   

    public function getContenuFormation(): ?string
    {
        return $this->contenu_Formation;
    }

    public function setContenuFormation(?string $contenu_Formation): self
    {
        $this->contenu_Formation = $contenu_Formation;

        return $this;
    }

    public function getLieuFormation(): ?string
    {
        return $this->lieuFormation;
    }

    public function setLieuFormation(?string $lieuFormation): self
    {
        $this->lieuFormation = $lieuFormation;

        return $this;
    }

    public function getCoutFormation(): ?string
    {
        return $this->coutFormation;
    }

    public function setCoutFormation(?string $coutFormation): self
    {
        $this->coutFormation = $coutFormation;

        return $this;
    }

    public function getMatSupp(): ?bool
    {
        return $this->matSupp;
    }

    public function setMatSupp(?bool $matSupp): self
    {
        $this->matSupp = $matSupp;

        return $this;
    }

    public function getSessionFormation(): ?SessionFormation
    {
        return $this->sessionFormation;
    }

    public function setSessionFormation(?SessionFormation $sessionFormation): self
    {
        $this->sessionFormation = $sessionFormation;

        return $this;
    }

    
}

src/Entity/PreInscription.php
<?php

namespace App\Entity;

use App\Repository\PreInscriptionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PreInscriptionRepository::class)
 */
class PreInscription
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Prospect::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $prospect;

    /**
     * @ORM\ManyToOne(targetEntity=ChargeDe::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $chargeDe;

    /**
     * @ORM\ManyToOne(targetEntity=CategFormation::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $categFormation;

    /**
     * @ORM\ManyToOne(targetEntity=Financement::class)
     * @ORM\JoinColumn(nullable=true)
     */
    private $financement;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $candidatMontantPartiel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomStructureFinancement;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isStructureFinancementValide;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProspect(): ?Prospect
    {
        return $this->prospect;
    }

    public function setProspect(Prospect $prospect): self
    {
        $this->prospect = $prospect;

        return $this;
    }

    public function getChargeDe(): ?ChargeDe
    {
        return $this->chargeDe;
    }

    public function setChargeDe(?ChargeDe $chargeDe): self
    {
        $this->chargeDe = $chargeDe;

        return $this;
    }

    public function getCategFormation(): ?CategFormation
    {
        return $this->categFormation;
    }

    public function setCategFormation(?CategFormation $categFormation): self
    {
        $this->categFormation = $categFormation;

        return $this;
    }

    public function getFinancement(): ?Financement
    {
        return $this->financement;
    }

    public function setFinancement(?Financement $financement): self
    {
        $this->financement = $financement;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCandidatMontantPartiel(): ?string
    {
        return $this->candidatMontantPartiel;
    }

    public function setCandidatMontantPartiel(?string $candidatMontantPartiel): self
    {
        $this->candidatMontantPartiel = $candidatMontantPartiel;

        return $this;
    }

    public function getNomStructureFinancement(): ?string
    {
        return $this->nomStructureFinancement;
    }

    public function setNomStructureFinancement(?string $nomStructureFinancement): self
    {
        $this->nomStructureFinancement = $nomStructureFinancement;

        return $this;
    }

    public function getIsStructureFinancementValide(): ?bool
    {
        return $this->isStructureFinancementValide;
    }

    public function setIsStructureFinancementValide(?bool $isStructureFinancementValide): self
    {
        $this->isStructureFinancementValide = $isStructureFinancementValide;

        return $this;
    }
}

src/Controller/PreInscriptionController.php
<?php

namespace App\Controller;

use App\Entity\PreInscription;
use App\Entity\Prospect;
use App\Form\PreInscriptionType;
use App\Repository\CategFormationRepository;
use App\Repository\ChargeDeRepository;
use App\Repository\FinancementRepository;
use App\Repository\PreInscriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/pre/inscription")
 */
class PreInscriptionController extends AbstractController
{
    /**
     * @Route("/", name="pre_inscription_index", methods={"GET"})
     */
    public function index(PreInscriptionRepository $preInscriptionRepository): Response
    {
        return $this->render('pre_inscription/index.html.twig', [
            'pre_inscriptions' => $preInscriptionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new/{id}", name="pre_inscription_new", methods={"GET","POST"})
     */
    public function new(Prospect $prospect,Request $request): Response
    {
        // affiche le template du form 

        return $this->render('pre_inscription/new.html.twig', [
            'prospect'=>$prospect,
            
        ]);
    }
     /**
     * @Route("/store/{id}", name="pre_inscription_store", methods={"GET","POST"})
     */
    public function store(Prospect $prospect,Request $request,
                        ChargeDeRepository $ChargeDeRepository,
                        FinancementRepository $financementRepository,
                        CategFormationRepository $categFormationRepository,
                        \Swift_Mailer $mailer): Response
    {
            $preInscription = new PreInscription();
            // recup de la date
            $date = new \DateTime('@'.strtotime('now'));
            // recup de "charge de "
            $idChargeDe = $request->get ('ChargeDe');
            $ChargesDe = $ChargeDeRepository->findBy(['id'=>$idChargeDe]);
            // si partiellement candidat
            $montant =$request->get ('montantCandidat');
            // si structure
            $nomStructure = $request->get ('nomStructure');
            // dd($nomStructure);
            // si paiement validé
            $validPaiement = $request ->get ('validePaiement');
                if($validPaiement){
                $validPaiement = true;
                }else{
                $validPaiement = false;
                }
            
            // recup de la categ de formation (i ou a)
            $idCategFormation = $request->get ('CategFormation');
            $CategFormations =$categFormationRepository->findBy (['id'=>$idCategFormation]);
            // dump($CategFormations[0]);
            //  recup du mode de paiement
            $idFinancement =$request->get ('financement');
            $financements =$financementRepository->findBy (['id'=>$idFinancement]);
           
        
            $entityManager = $this->getDoctrine()->getManager();
            // set des colonnes de la table préinscription
            $preInscription->setCreatedAt($date);
            $preInscription->setProspect($prospect);
            $preInscription->setCandidatMontantPartiel($montant);
            $preInscription->setNomStructureFinancement($nomStructure);
            $preInscription->setIsStructureFinancementValide($validPaiement);
            
            
            
            $preInscription->setCategFormation($CategFormations[0]);
            $preInscription->setChargeDe($ChargesDe[0]);
            $preInscription->setFinancement($financements[0]);

            $entityManager->persist($preInscription);
            $entityManager->flush();
            
            // envoie mail confirmation
            $message = (new \Swift_Message('inscription'))
                // On attribue l'expéditeur
                ->setFrom('vxforest@gmail.com')

                // On attribue le destinataire
                ->setTo($prospect->getEmail())
               
                // On crée le texte avec la vue
                ->setBody(
                    
                        'Merci pour votre pré_inscription, nous vous recontacterons dès que possible.
                        Ares Formation'
                    ,
                    'text/html'
                )
                ;
                
                $mailer->send($message);
             
            return $this->redirectToRoute('pre_inscription_confirmation',['id'=> $preInscription->getId()]);
       
        return $this->render('pre_inscription/new.html.twig', [
            'prospect'=>$prospect,
            'pre_inscription' => $preInscription,
            
        ]);
    }
    

    /**
     * @Route("/{id}", name="pre_inscription_confirmation", methods={"GET"})
     */
    public function confirmation(PreInscription $preInscription): Response
    {
        
        return $this->render('pre_inscription/confirmation.html.twig', [
           
            'pre_inscription' => $preInscription,
        ]);
    }
    
    /**
     * @Route("/{id}/edit", name="pre_inscription_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, PreInscription $preInscription): Response
    {
        $form = $this->createForm(PreInscriptionType::class, $preInscription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pre_inscription_index');
        }

        return $this->render('pre_inscription/edit.html.twig', [
            'pre_inscription' => $preInscription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pre_inscription_delete", methods={"DELETE"})
     */
    public function delete(Request $request, PreInscription $preInscription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$preInscription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($preInscription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pre_inscription_index');
    }
}

templates/pre_inscription/_delete_form.html.twig
<form method="post" action="{{ path('pre_inscription_delete', {'id': pre_inscription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pre_inscription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pre_inscription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New PreInscription{% endblock %}

{% block body %}
<div class="container">
  <h1 class="show">En route pour la pré-inscription</h1>

  <form id="preinscription-form" method="post" action="{{path("pre_inscription_store",{'id':prospect.id})}}">
      <input type="hidden" name="prospect_id" value="{{ prospect.id }}" >
       {# <input type="hidden" name="prospect_date" value="{{ prospect.id }}" > #}
     
      <div class="form-check-inline">
      
        
        <input class="form-check-input" name="CategFormation" type="radio" value="1" id="exampleRadios1" checked>
        <label class="form-check-label"  for="exampleRadios1" value="1">
        Contrat de formation (formation initiale)
        </label>
      </div>
      <div class="form-check-inline">
        
       
        <input class="form-check-input" name="CategFormation" type="radio" value="2" id="exampleRadios2" >
         <label class="form-check-label" for="exampleRadios2">
          Convention de formation (formation en alternance)
        </label>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputFormation">Nom de la formation</label>
          <input type="text" class="form-control" id="inputFormation" value="{{prospect.parcours.formation.type}}">
        </div>
      
     
        <div class="form-group col-md-6">
          <label for="inputDuree">Durée de la formation</label>
          <input type="text" class="form-control" id="inputDuree" value="{{prospect.parcours.formation.duree}}">
        </div>
      </div>
      
     
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputSession">Session</label>
          <input type="text" class="form-control" id="inputSession" value="{{prospect.parcours.formation.sessionFormation.nom}}" >
        </div>
      
      
        <div class="form-group col-md-6">
          
           <label for="inputLieu">Lieu de la formation </label>
          <input type="text" class="form-control" id="inputLieu" value="{{prospect.parcours.formation.lieuFormation}}">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-12">
          <label for="inputContenu">Contenu de la formation : </label>
          <input type="textarea" class="form-control" id="inputContenu" value="{{prospect.parcours.formation.contenuFormation}}" >       
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputNom">NOM :</label>
          <input type="text" class="form-control" id="inputNom"value="{{prospect.nom}}">
        </div>
        <div class="form-group col-md-6">
          <label for="inputPrenom">PRENOM :</label>
          <input type="text" class="form-control" id="inputPrenom" value="{{prospect.prenom}}">
        </div>
      </div>
      <div class="form-group">
        <label for="inputAddress">Adresse :</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St"value="{{prospect.adresse}}">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Ville :</label>
          <input type="text" class="form-control" id="inputCity" value="{{prospect.ville}}">
        </div>
        <div class="form-group col-md-6">
          <label for="inputState">CP :</label>
          <input id="inputState" class="form-control"value="{{prospect.cp}}">
        </div>
      </div>
     <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputTel">Tel :</label>
          <input type="text" class="form-control" id="inputTel" value="{{prospect.tel}}">
        </div>
        <div class="form-group col-md-6">
          <label for="inputMail">Mail :</label>
          <input id="inputMail" class="form-control"value="{{prospect.email}}">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputDateNaissance">Né(e) le :</label>
          <input type="text" class="form-control" id="inputDateNaissance" value="{{prospect.dateNaissance|date("m/d/y",false)}}">
        </div>
        <div class="form-group col-md-6">
          <label for="inputLieuNaissance">à :</label>
          <input id="inputLieuNaissance" class="form-control"value="{{prospect.lieuNaissance}}">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Dépt naissance</label>
          <input type="text" class="form-control" id="inputCity" value="{{prospect.deptNaissance}}">
        </div>
        <div class="form-group col-md-6">
          <label for="inputState">Nationalité :</label>
          <input id="inputState" class="form-control"value="{{prospect.nationalite}}">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="inputDiplomeCours">Diplôme en cours</label>
          <input type="text" class="form-control" id="inputDiplomeCours" value="{{prospect.parcours.encoursDiplome}}" placeholder="à compléter">
        </div>
        <div class="form-group col-md-4">
          <label for="inputDiplomeObtenu">Diplôme obtenu :</label>
          <input id="inputDiplomeObtenu" class="form-control"value="{{prospect.parcours.dernierDiplome}}">
            
        </div>
        <div class="form-group col-md-4">
          <label for="inputHandicap">Handicap :</label>
          <input id="inputHandicap" class="form-control"value="{{prospect.parcours.handicap}}">
            
        </div>
        
      </div>
    
      <div class="form-group col-md-4">
        <label for="inputCoutFormation">Coût de la formation</label>
        <input type="text" class="form-control" id="inputCoutFormation"  value="{{prospect.parcours.formation.coutFormation}}">
      
      <div class="form-check">
 
       
        {% if (prospect.parcours.formation.matSupp) %}
         <label for="form-check-label">Matériel supplémentaire  </label>
        <input class="form-check-input-left" type="checkbox" id="MatCheck1" checked>
               
        {% endif %}    
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-12">
        <label  for="ChargeDe">
          <h6>A la charge de : </h6>
          </label>
        </div>
        
      </div>
      <div class="form-row">
         <div class="form-group col-md-12">
        <div class="form-check-inline">
          
          <input class="form-check-input" name="ChargeDe" type="radio" checked="checked" value="1" id="exampleRadios3">
          <label class="form-check-label" for="exampleRadios3" >
            Intégralement du candidat
          </label>
        </div>
        <div class="form-check-inline">
          
          <input class="form-check-input" name="ChargeDe" type="radio" value="2" id="exampleRadios4" checked="checked" onclick="txtInput()">
          <label class="form-check-label" for="exampleRadios4">
            Partiellement du candidat, 
          
          </label>
          <div class="form-group col-md-12">
          {# {% if (pre_inscription.chargeDe.id as "(2)") %} #}
          <div id='montantpartiel'>  
         <label for="inputmontantpartiel">Montant :</label>
          <input type="text" class="form-control" id="inputmontantpartiel" name="montantCandidat" value="">
          {# {% endif %} #}
          </div>
        </div>

        </div>
        <div class="form-check-inline">
          
          <input class="form-check-input" name="ChargeDe" type="radio" value="3" id="exampleRadios5tri" checked="checked" onclick="txtstructure();">
          <label class="form-check-label" for="exampleRadios5tri">
          Structure externe : 
          </label>
          <div id="nomstructure">
            <div class="form-group col-md-12 ">
                <label for="nomstructure">Nom :</label>
                <input type="text" class="form-control" name="nomStructure" id="nomstructurefinan"  value="">
            </div>
            <div class="form-check-inline">
              <label class="form-check-label" for="exampleRadios5bis">
                Paiement validé par la structure
                </label>
                <input class="form-check-input-left" name="validePaiement" type="radio" value="true" id="exampleRadios5bis" >
            </div>
          </div>
         
        
        </div>
        </div>
        
          <label  for="Financement">
           <h6> Mode de paiement de la formation : </h6>
            </label>
        
      </div>
      <div class="form-row">
        <div class="form-group col-md-12">
          <div class="form-check">
            
            <input class="form-check-input" name="financement"  type="radio" value="1" id="exampleRadios6" checked="checked">
            <label class="form-check-label " for="exampleRadios6">
              Alternance (Alpha PRIMO)
            </label>
          
          </div>
          <div class="form-check">
            
            <input class="form-check-input" name="financement" type="radio" value="2" id="exampleRadios7" >
            <label class="form-check-label" for="exampleRadios7">
              CPF (Alpha PRIMO)
            </label>
          </div>
          <div class="form-check">
            
            <input class="form-check-input"name="financement"  type="radio" value="3" id="exampleRadios8" >
            <label class="form-check-label" for="exampleRadios8">
            Continue (Alpha PRIMO)
            </label>
          </div>
          <div class="form-check">
            
            <input class="form-check-input" name="financement"  type="radio" value="4" id="exampleRadios9" >
            <label class="form-check-label" for="exampleRadios9">
            Formation initiale Conduisant à un diplôme d'état (GROUPE ARES MATHZAP FORMATION)
            </label>
          </div>
          <div class="form-check">
            
            <input class="form-check-input"name="financement" type="radio" value="5" id="exampleRadios10" >
            <label class="form-check-label" for="exampleRadios10">
            Formation privée (GROUPE ARES MATHZAP FORMATION)
            </label>
          </div>
        </div>
      </div>
    
  
    <button id="preinscription" type="submit" class="btn btn-primary btn-lg float-right">Envoyer<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
      <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
      </svg>
    </button>
      

  </form>
  

    {# <a href="{{ path('pre_inscription_index') }}">back to list</a> #}
</div>
{% endblock %}

templates/pre_inscription/recappreinsc.html.twig
{% extends 'base.html.twig' %}

{% block title %}PreInscription{% endblock %}

 
{% block body %}

    <body>
        <div class="container">
  <h2 id="pdf" >Formulaire de pré-inscription </h2>

  <form id="preinscription-form" method="post" action="{{path("pre_inscription_store",{'id':preinscription.prospect.id})}}">
     
      <div id="categFormation">
     
        {# <input class="form-check-input" name="CategFormation" type="radio" value="1" id="exampleRadios1" checked> #}
        <p>{{preinscription.categFormation.nom}}</p>
        
       
      </div>
      <table class="table table-bordered">
      <tbody>
      
        <tr>
          <th scope="row">Nom de la formation</th>
          <td>{{preinscription.prospect.parcours.formation.type}}</td>
          <th scope="row">Durée de la formation</th>
          <td>{{preinscription.prospect.parcours.formation.duree}}</td>
        </tr>
      </tbody>
     </table>
     <table class="table table-bordered">
      <tbody>
      
            <tr>
          <th scope="row">Session</th>
          <td class="text-center">{{preinscription.prospect.parcours.formation.sessionFormation.nom}}</td>
        </tr>
      </tbody>
     </table>

     <table class="table table-bordered">
      <tbody>
      
          <tr>
          <th scope="row">Lieu de la formation</th>
          <td class="text-center">{{preinscription.prospect.parcours.formation.lieuFormation}}</td>
        </tr>

      </tbody>
     </table>
     <table class="table table-bordered">
      <tbody>
      
          <tr>
          <th scope="row">Contenu de la formation</th>
          <td class="text-center">{{preinscription.prospect.parcours.formation.contenuFormation}}</td>
        </tr>

      </tbody>
     </table>
         <table class="table table-bordered">
      <tbody>
      
        <tr>
          <th scope="row">NOM</th>
          <td>{{preinscription.prospect.nom}}</td>
          <th scope="row">PRENOM</th>
          <td>{{preinscription.prospect.prenom}}</td>
        </tr>
      </tbody>
     </table>
      <table class="table table-bordered">
        <tbody>
        
            <tr>
            <th scope="row">Adresse</th>
            <td class="text-center">{{preinscription.prospect.adresse}}</td>
          </tr>

        </tbody>
     </table>
      <table class="table table-bordered">
        <tbody>
        
          <tr>
            <th scope="row">CP</th>
            <td>{{preinscription.prospect.cp}}</td>
            <th scope="row">Ville</th>
            <td>{{preinscription.prospect.ville}}</td>
          </tr>
        </tbody>
     </table>
     <table class="table table-bordered">
        <tbody>
        
          <tr>
            <th scope="row">Tel</th>
            <td>{{preinscription.prospect.tel}}</td>
            <th scope="row">Mail</th>
            <td>{{preinscription.prospect.email}}</td>
          </tr>
        </tbody>
     </table>
   
     <table class="table table-bordered">
        <tbody>
        
          <tr>
            <th scope="row">Né(e) le</th>
            <td>{{preinscription.prospect.lieuNaissance}}</td>
            <th scope="row">à</th>
            <td>{{preinscription.prospect.lieuNaissance}}</td>
          </tr>
        </tbody>
     </table>
    <table class="table table-bordered">
        <tbody>
        
          <tr>
            <th scope="row">Dépt naissance</th>
            <td>{{preinscription.prospect.deptNaissance}}</td>
            <th scope="row">Nationalité </th>
            <td>{{preinscription.prospect.nationalite}}</td>
          </tr>
        </tbody>
     </table>
    <table class="table table-bordered">
      <tbody>
      
        <tr>
          <th scope="row">Diplôme en cours</th>
          <td>{{preinscription.prospect.parcours.encoursDiplome}}      </td>
          <th scope="row">Diplôme obtenu </th>
          <td>{{preinscription.prospect.parcours.dernierDiplome}}</td>
          <th scope="row">Handicap</th>
          <td class="text-center">{{preinscription.prospect.parcours.handicap}}</td>
        </tr>

      </tbody>
     </table>
      <table class="table table-bordered">
      <tbody>
      
          <tr>
          <th scope="row">Coût de la formation</th>
          <td class="text-center">{{preinscription.prospect.parcours.formation.coutFormation}}</td>
          
        </tr>
 
      </tbody>
     </table>
            <div class="form-check">
 
       
        {% if (preinscription.prospect.parcours.formation.matSupp) %}
         <label for="form-check-label">Matériel supplémentaire  </label>
        <input class="form-check-input-left" type="checkbox" id="MatCheck1" checked>
               
        {% endif %}    
      </div>
       
    
      
      <h6>A la charge de : </h6>
      
      
          <form>
          <input type="hidden" id="inputid" value="{{preinscription.chargeDe.id}}">
          </form>
          {% if preinscription.chargeDe.id  == 2 %}
            <div>
            <p class="repChoice"> {{preinscription.chargeDe.libelle}}   {{preinscription.candidatMontantPartiel}}</p>
            
             </div> 
                 
            
         
          
      {% elseif preinscription.chargeDe.id  == 3  %}  
          <div>
            <p class="repChoice"> {{preinscription.chargeDe.libelle}}  {{preinscription.nomStructureFinancement}}</p>
            
            
            {% if (preinscription.isStructureFinancementValide) %}
                <div class="form-check-inline">
                
                  <label class="form-check-label" for="exampleRadios5bis">
                    Paiement validé par la structure
                    </label>
                    <input class="form-check-input-left" name="validePaiement" type="radio" value="true" id="exampleRadios5bis"  checked>
                </div>
            {% endif %}
          </div> 
        {% else %}
          <div>
            <p class="repChoice"> {{preinscription.chargeDe.libelle}}</p>
          </div>
    
        {% endif %}
        
      
         
       
      <h6> Mode de paiement de la formation : </h6>
      <div>
      <p class="repChoice">  {{preinscription.financement.nom}}</p>
      </div>    
        
     
        <div class="validation">
        <p> Fait à : {{preinscription.prospect.ville}}  </p>
        <p> le : {{ 'now'|date('Y-m-d') }} </p>
        <p> Signature</p>
        </div>
            
        
      

  

   
</div>
 
{% endblock %}