src/Entity/Parcours.php
<?php

namespace App\Entity;

use App\Repository\ParcoursRepository;
use Doctrine\ORM\Mapping as ORM;




/**
 * @ORM\Entity(repositoryClass=ParcoursRepository::class)
 */
class Parcours
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numPoleEmploi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dernierDiplome;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dernierEmploi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dernier_contrat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $handicap;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $remarque;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomReferent;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mailReferent;

    /**
     * @ORM\ManyToOne(targetEntity=Structure::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $structure;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $formation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $encoursDiplome;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumPoleEmploi(): ?string
    {
        return $this->numPoleEmploi;
    }

    public function setNumPoleEmploi(?string $numPoleEmploi): self
    {
        $this->numPoleEmploi = $numPoleEmploi;

        return $this;
    }

    public function getCpf(): ?string
    {
        return $this->cpf;
    }

    public function setCpf(?string $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getDernierDiplome(): ?string
    {
        return $this->dernierDiplome;
    }

    public function setDernierDiplome(?string $dernierDiplome): self
    {
        $this->dernierDiplome = $dernierDiplome;

        return $this;
    }

    public function getDernierEmploi(): ?string
    {
        return $this->dernierEmploi;
    }

    public function setDernierEmploi(?string $dernierEmploi): self
    {
        $this->dernierEmploi = $dernierEmploi;

        return $this;
    }

    public function getDernierContrat(): ?string
    {
        return $this->dernier_contrat;
    }

    public function setDernierContrat(?string $dernier_contrat): self
    {
        $this->dernier_contrat = $dernier_contrat;

        return $this;
    }

    public function getHandicap(): ?string
    {
        return $this->handicap;
    }

    public function setHandicap(?string $handicap): self
    {
        $this->handicap = $handicap;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(?string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getNomReferent(): ?string
    {
        return $this->nomReferent;
    }

    public function setNomReferent(?string $nomReferent): self
    {
        $this->nomReferent = $nomReferent;

        return $this;
    }

    public function getMailReferent(): ?string
    {
        return $this->mailReferent;
    }

    public function setMailReferent(?string $mailReferent): self
    {
        $this->mailReferent = $mailReferent;

        return $this;
    }

    public function getStructure(): ?Structure
    {
        return $this->structure;
    }

    public function setStructure(?Structure $structure): self
    {
        $this->structure = $structure;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }
    
    public function setId(): self
    {	
    $id = md5(random_bytes(50));
    $this->id = $id;

    return $this;
    }

    public function getEncoursDiplome(): ?string
    {
        return $this->encoursDiplome;
    }

    public function setEncoursDiplome(?string $encoursDiplome): self
    {
        $this->encoursDiplome = $encoursDiplome;

        return $this;
    }
}

src/Form/ParcoursType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use App\Entity\Parcours;
use App\Entity\Structure;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class ParcoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('numPoleEmploi')
            ->add('cpf')
            ->add('dernierDiplome')
            ->add('encoursDiplome')
            ->add('dernierEmploi')
            ->add('dernier_contrat')
            ->add('handicap',ChoiceType::class, [
                'choices'  => [
                 
                    'Non' => false,
                    'Oui' => true,
                ],
                ])
            ->add('remarque')
            // ->add('cv',ChoiceType::class, [
            //     'choices'  => [
                 
            //     'Oui' => true,
            //     'Non' => false,
            //     ],
            //     ])
            ->add('cv',FileType::class, [
            'label'  => 'Cv (fichier PDF)',
            'mapped' => false,
            'required'=>false,
            'constraints'=>[
                            new File([
                                'mimeTypes' => [
                                    'application/pdf',
                                    'application/x-pdf',

                                ],
                                //  'mimeTypeMessage' =>'merci de télécharger un document PDF',
                                ])
                            ]
            ])
            ->add('nomReferent')
            ->add('mailReferent')
            ->add('structure',EntityType::class, array(
                    'class' => Structure::class,
                    'choice_label' => 'nom',
                    'multiple'  => false,
            ))
            ->add('formation',EntityType::class, array(
                    'class' => Formation::class,
                    'choice_label' => 'type',
                    'multiple'  => false,
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Parcours::class,
        ]);
    }
}

src/Controller/ParcoursController.php
<?php

namespace App\Controller;

use App\Entity\Parcours;
use App\Form\ParcoursType;
use App\Repository\ParcoursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;



/**
 * @Route("/parcours")
 */
class ParcoursController extends AbstractController
{
    /**
     * @Route("/", name="parcours_index", methods={"GET"})
     */
    public function index(ParcoursRepository $parcoursRepository): Response
    {
        return $this->render('parcours/index.html.twig', [
            'parcours' => $parcoursRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="parcours_new", methods={"GET","POST"})
     */
    public function new(Request $request,SluggerInterface $slugger): Response
    {
        $parcour = new Parcours();
        $form = $this->createForm(ParcoursType::class, $parcour);
        $form->handleRequest($request);
          
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $parcour->setId();

            // upload files (cv)
            $cvFile =$form->get('cv')->getData();
            if ($cvFile) {
                $originalFilename = pathinfo($cvFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$cvFile->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $cvFile ->move(
                        $this->getParameter('brochures_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'cv name' property to store the PDF file name
                // instead of its contents
                $parcour->setCv($newFilename);
            }

            $entityManager->persist($parcour);
            $entityManager->flush();

            return $this->redirectToRoute('prospect_new',['id'=> $parcour->getId()]);
        }

        return $this->render('parcours/new.html.twig', [
            'parcour' => $parcour,
            
            'form' => $form->createView(),
            
        ]);
    }

    /**
     * @Route("/{id}", name="parcours_show", methods={"GET"})
     */
    public function show(Parcours $parcour): Response
    {
        return $this->render('parcours/show.html.twig', [
            'parcour' => $parcour,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="parcours_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Parcours $parcour): Response
    {
        $form = $this->createForm(ParcoursType::class, $parcour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('parcours_index');
        }

        return $this->render('parcours/edit.html.twig', [
            'parcour' => $parcour,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="parcours_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Parcours $parcour): Response
    {
        if ($this->isCsrfTokenValid('delete'.$parcour->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($parcour);
            $entityManager->flush();
        }

        return $this->redirectToRoute('parcours_index');
    }
}

templates/parcours/_delete_form.html.twig
<form method="post" action="{{ path('parcours_delete', {'id': parcour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ parcour.id) }}">
    <a class="btn btn-danger btn-lg "  class="btn">Supprimer</a>
</form>

templates/parcours/_form.html.twig
<div class="container">
    {{ form_start(form) }}
   <div class="form-row">
        <div class="form-group col-md-4">
            {{form_label(form.numPoleEmploi, 'Votre numéro Pôle Emploi', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.numPoleEmploi, {'attr': {'class': "form-control", 'placeholder': "N° Pôle Emploi"}}) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{form_label(form.cpf, 'CPF (montant disponible)', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.cpf, {'attr': {'class': "form-control", 'placeholder': "CPF"}}) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3">
            {{form_label(form.dernierDiplome, 'votre dernier diplôme obtenu', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.dernierDiplome, {'attr': {'class': "form-control", 'placeholder': "dernier Diplome"}}) }}
        </div>
        <div class="form-group col-md-3">
            {{form_label(form.encoursDiplome, 'votre diplôme en cours', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.encoursDiplome, {'attr': {'class': "form-control", 'placeholder': "Diplôme en cours"}}) }}
        </div>
        <div class="form-group col-md-3">
            {{form_label(form.dernierEmploi, 'Votre dernierEmploi', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.dernierEmploi, {'attr': {'class': "form-control", 'placeholder': "dernierEmploi"}}) }}
        </div>
        <div class="form-group col-md-3">
            {{form_label(form.dernier_contrat, 'Votre votre dernier contrat ', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.dernier_contrat, {'attr': {'class': "form-control", 'placeholder': "votre dernier contrat (CDI, CDD...)"}}) }}
        </div>
    </div>
    <div class="form-row">    
        <div class="form-group col-md-4">
            {{form_label(form.handicap, 'situation de handiap', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.handicap, {'attr': {'class': "form-control"}}) }}
        </div>
    
        <div class="form-group col-md-6">
            {{form_label(form.remarque, 'remarque', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.remarque, {'attr': {'class': "form-control", 'placeholder': "explications à apporter"}}) }}
        </div>
    </div>
     <div class="form-row"> 
        <div class="form-group col-md-6">
            {{form_label(form.cv, 'télécharger votre CV', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.cv, {'attr': {'class': "form-control"}}) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-4">
            {{form_label(form.nomReferent, 'le Nom de votre conseiller', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.nomReferent, {'attr': {'class': "form-control", 'placeholder': "nom de votre conseiller Pôle Emploi, etc..."}}) }}
        </div>
  
        <div class="form-group col-md-3">
            {{form_label(form.mailReferent, 'Email du referent', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.mailReferent, {'attr': {'class': "form-control", 'placeholder': "Email du referent"}}) }}
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-3">
            {{form_label(form.structure, 'Structure dont vous dépendez', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.structure, {'attr': {'class': "form-control", 'placeholder': "AFPA,..."}}) }}
        </div>
        <div class="form-group col-md-6">
            {{form_label(form.formation, 'je suis interessé(e) par la formation :', { 'attr': {'class': 'foo'} }) }}
            {{ form_widget(form.formation, {'attr': {'class': "form-control", 'placeholder': "je suis interessé(e) par la formation :"}}) }}
        </div>
    </div>
    
    <button class="btn btn-info btn-lg float-right">{{ button_label|default('Mes Coordonnées') }}  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
    <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
    </svg></button>
    {# <a class="btn btn-outline-info btn-lg float-right" href="{{ path('prospect_new',{'id': parcour.id}) }}">Mes coordonnées   <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
    <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
    </svg></a> #}
</div>

{{ form_end(form) }}

templates/parcours/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Parcours{% endblock %}

{% block body %}
    <div class="container">
    <h1 class="show">Modifier mon parcours</h1>

    {{ include('parcours/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    {# <a href="{{ path('parcours_index') }}">back to list</a> #}

    {{ include('parcours/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/parcours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parcours index{% endblock %}

{% block body %}
<div class="container">
    <h1 class="show">Parcours index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NumPoleEmploi</th>
                <th>Cpf</th>
                <th>DernierDiplome</th>
                <th>DernierEmploi</th>
                <th>Dernier_contrat</th>
                <th>Handicap</th>
                <th>Remarque</th>
                <th>Cv</th>
                <th>NomReferent</th>
                <th>MailReferent</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for parcour in parcours %}
            <tr>
                <td>{{ parcour.id }}</td>
                <td>{{ parcour.numPoleEmploi }}</td>
                <td>{{ parcour.cpf }}</td>
                <td>{{ parcour.dernierDiplome }}</td>
                <td>{{ parcour.dernierEmploi }}</td>
                <td>{{ parcour.dernierContrat }}</td>
                <td>{{ parcour.handicap }}</td>
                <td>{{ parcour.remarque }}</td>
                <td>{{ parcour.cv }}</td>
                <td>{{ parcour.nomReferent }}</td>
                <td>{{ parcour.mailReferent }}</td>
                <td>
                    <a href="{{ path('parcours_show', {'id': parcour.id}) }}">show</a>
                    <a href="{{ path('parcours_edit', {'id': parcour.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('parcours_new') }}">Create new</a>
</div>
{% endblock %}

templates/parcours/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Parcours{% endblock %}

{% block body %}
    <div class="container">
    <h1 class="show"> Votre parcours nous intéresse !</h1>

    {{ include('parcours/_form.html.twig') }}

    </div>

    {# <a href="{{ path('parcours_index') }}">back to list</a> #}
{% endblock %}

templates/parcours/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Parcours{% endblock %}

{% block body %}
<div class="container">
    <h1 class="show">Parcours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ parcour.id }}</td>
            </tr>
            <tr>
                <th>NumPoleEmploi</th>
                <td>{{ parcour.numPoleEmploi }}</td>
            </tr>
            <tr>
                <th>Cpf</th>
                <td>{{ parcour.cpf }}</td>
            </tr>
            <tr>
                <th>DernierDiplome</th>
                <td>{{ parcour.dernierDiplome }}</td>
            </tr>
            <tr>
                <th>DernierEmploi</th>
                <td>{{ parcour.dernierEmploi }}</td>
            </tr>
            <tr>
                <th>Dernier_contrat</th>
                <td>{{ parcour.dernierContrat }}</td>
            </tr>
            <tr>
                <th>Handicap</th>
                <td>{{ parcour.handicap }}</td>
            </tr>
            <tr>
                <th>Remarque</th>
                <td>{{ parcour.remarque }}</td>
            </tr>
            <tr>
                <th>Cv</th>
                <td>{{ parcour.cv }}</td>
            </tr>
            <tr>
                <th>NomReferent</th>
                <td>{{ parcour.nomReferent }}</td>
            </tr>
            <tr>
                <th>MailReferent</th>
                <td>{{ parcour.mailReferent }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('parcours_index') }}">back to list</a>

    <a href="{{ path('parcours_edit', {'id': parcour.id}) }}">edit</a>
</div>
    {{ include('parcours/_delete_form.html.twig') }}
{% endblock %}